"""Create boardroom_sessions table

Revision ID: a2c3b67ac161
Revises: 
Create Date: 2026-05-01 20:27:53.054814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c3b67ac161'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardroom_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('session_timestamp', sa.DateTime(), nullable=True),
    sa.Column('technical_analysis', sa.String(), nullable=True),
    sa.Column('macro_analysis', sa.String(), nullable=True),
    sa.Column('risk_analysis', sa.String(), nullable=True),
    sa.Column('executive_summary', sa.String(), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardroom_sessions_id'), 'boardroom_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_boardroom_sessions_ticker'), 'boardroom_sessions', ['ticker'], unique=False)
    op.create_index(op.f('ix_boardroom_sessions_user_id'), 'boardroom_sessions', ['user_id'], unique=False)
    op.create_table('user_stock_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker', name='uq_user_stock_targets_user_ticker')
    )
    op.create_index(op.f('ix_user_stock_targets_id'), 'user_stock_targets', ['id'], unique=False)
    op.create_index(op.f('ix_user_stock_targets_ticker'), 'user_stock_targets', ['ticker'], unique=False)
    op.create_index(op.f('ix_user_stock_targets_user_id'), 'user_stock_targets', ['user_id'], unique=False)
    op.create_index('ix_user_stock_targets_user_ticker', 'user_stock_targets', ['user_id', 'ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_stock_targets_user_ticker', table_name='user_stock_targets')
    op.drop_index(op.f('ix_user_stock_targets_user_id'), table_name='user_stock_targets')
    op.drop_index(op.f('ix_user_stock_targets_ticker'), table_name='user_stock_targets')
    op.drop_index(op.f('ix_user_stock_targets_id'), table_name='user_stock_targets')
    op.drop_table('user_stock_targets')
    op.drop_index(op.f('ix_boardroom_sessions_user_id'), table_name='boardroom_sessions')
    op.drop_index(op.f('ix_boardroom_sessions_ticker'), table_name='boardroom_sessions')
    op.drop_index(op.f('ix_boardroom_sessions_id'), table_name='boardroom_sessions')
    op.drop_table('boardroom_sessions')
    # ### end Alembic commands ###
